# Generated by Django 5.2.14 on 2026-05-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StartupIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.TextField()),
                ('result', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('demand', models.IntegerField()),
                ('competition', models.IntegerField()),
                ('feasibility', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
